# Generated by Django 4.1.5 on 2023-01-21 17:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubgAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubg_id', models.IntegerField()),
                ('rp', models.IntegerField(blank=True, default=0)),
                ('xsuite', models.IntegerField(blank=True, default=0)),
                ('mifik_kiyim', models.IntegerField(blank=True, default=0)),
                ('avtomat', models.IntegerField(blank=True, default=0)),
                ('kill_chat', models.IntegerField(blank=True, default=0)),
                ('granada', models.IntegerField(blank=True, default=0)),
                ('sumka', models.IntegerField(blank=True, default=0)),
                ('kaska', models.IntegerField(blank=True, default=0)),
                ('parachute', models.IntegerField(blank=True, default=0)),
                ('mashina', models.IntegerField(blank=True, default=0)),
                ('samalyot', models.IntegerField(blank=True, default=0)),
                ('vertalyot', models.IntegerField(blank=True, default=0)),
                ('personaj', models.IntegerField(blank=True, default=0)),
                ('emoji', models.IntegerField(blank=True, default=0)),
                ('titul', models.IntegerField(blank=True, default=0)),
                ('hayvon', models.IntegerField(blank=True, default=0)),
                ('narxi', models.FloatField()),
                ('instagram', models.CharField(blank=True, max_length=30)),
                ('telegram', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to='pubg_account/images/')),
                ('video', models.FileField(upload_to='pubg_account/videos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blogpost_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pubg_account.pubgaccount')),
            ],
        ),
    ]
